### ISSUE TITLE
Typescript - exporting Layer type

### ISSUE THREAD

**Issue by deanWombourne** [amzn/sketch-constructor#69]
Hi.

I'm trying to write a function in typescript which has a Layer as one of it's parameters, but typescript is complaining that the Layer type isn't publicly exported. It's not wrong, in index.js it's not in the list of exports.

Is there any reason why Layer isn't exported?

Or, is there a way I should be specifying the Layer type - am I doing it wrong?

I'm trying

```typescript
import sketch from 'sketch-constructor'

// The error is in this function declaration.
function myFunction(layer: sketch.Layer) {
    .. code ...
}
```

I'm using sketch-constructor@1.11.1, npm 6.13.0 and node v12.12.0.

**Comment by Means88** [comment]
I didn't export `Layer` because it is not exported in `index.js`, and it may be used incorrectly like 
```typescript
const layer = new sketch.Layer();  //  <--  module_1.Layer is not a constructor
```

You can try 
```typescript
import Layer = require('sketch-constructor/models/Layer');
```
instead if you need the `Layer` type

or maybe we can just export the `Layer` class, how do you think? @dbanksdesign

**Comment by dbanksdesign** [comment]
Yea we could export the Layer class. I believe the reason we did not initially is because it is an abstract class and not meant to be actually instantiated. In a Sketch document there is no "layer" object, but instead layer-like objects like Group, Text, etc. 

Looking at @deanWombourne's code there does seem to be a valid use case for exporting the Layer type if you want to define a method that accepts a Layer-like type. If we exported the Layer type definition, would that work as expected if that method were to accept a Group for instance?

**Comment by L2jLiga** [comment]
>  it is an abstract class and not meant to be actually instantiated.

Hence we can mark it as abstract in typings at least?

**Comment by Means88** [comment]
Export type of `Layer` only in #74 

@L2jLiga There is a little difference between type and abstract class: the former one only has a type definition and the latter one means developers can extend from it. So I think it's more accurately to use a type instead of an abstract class. How do you think about it?

---

>  If we exported the Layer type definition, would that work as expected if that method were to accept a Group for instance?

@dbanksdesign Yes, anything inherits from `Layer` (explicitly and inexplicitly) is acceptable in where a `Layer` is required.

**Comment by L2jLiga** [comment]
> So I think it's more accurately to use a type instead of an abstract class. How do you think about it?

Also fine for me :)
