### ISSUE TITLE
Question: Creating Rectangles with rounded Corners

### ISSUE THREAD

**Issue by Bartz0210** [amzn/sketch-constructor#76]
Is there a way to set a Borderradius, when calling `new Rectangle()`?
I could not figure out a way to set the value and there is no despriction in the documentation

**Comment by reld** [comment]
Same issue here 👍

**Comment by eeegor** [comment]
@Bartz0210 @reld the problem is that the cornerRadius property is not propagated properly in the constructor of the [Rectangle](https://github.com/amzn/sketch-constructor/blob/4fc6fe2cf6cde091eeadfebad3f995485233e9b0/models/Rectangle/Rectangle.js#L63) model, so it's currently missing 😢 

Currently:
```javascript
points: points.map((point, index) =>
    new CurvePoint({
        curveFrom: point,
        curveTo: point,
        point,
    })
),
```

Should be something like this:
```javascript
points: points.map((point, index) =>
    new CurvePoint({
        cornerRadius: (Array.isArray(args.cornerRadius) ? args.cornerRadius[index] : args.cornerRadius) || 0,
        curveFrom: point,
        curveTo: point,
        point,
    })
),
```

Then you could pass either a single value for a fixed radius e.g. `4` or an array like `[0, 4, 8, 12]` for multiple borders.

If I'll manage in the next days, i'll propose a pull request to fix this one 😃

**Comment by jorgecasar** [comment]
I made the PR #95 to allow to override the cornerRadius to avoid to define the entire points.

With this approach you need to define points as follow.

`const points = ['{0, 0}', '{1, 0}', '{1, 1}', '{0, 1}'];`

Other solution could be to expose the point as static getter of the Rectangle Class to avoid magic arrays in the code.
